version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: bbdd_alumnos
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
      MYSQL_DATABASE: tienda_calzado
    ports:
      - "3306:3306"
    volumes:
      - ./Creaciones:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    networks:
      - db_network
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:

networks:
  db_network:
    driver: bridge
